# Generated by Django 2.1 on 2018-09-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myactivity',
            name='mytime',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='myactivity',
            name='person',
        ),
        migrations.AddField(
            model_name='myactivity',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Management.Volunteer'),
        ),
    ]
